AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: escoladesoftware_blog_blogpost_backend
Parameters:
  BucketName:
    Description: S3 Bucket Name
    Type: String
  Environment:
    Description: Environment
    Type: String

Resources:
  BlogPostContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref Environment, !Ref BucketName]]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  BlogPostContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BlogPostContentBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:PutObject
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${BlogPostContentBucket}
              - !Sub arn:aws:s3:::${BlogPostContentBucket}/*
            Principal:
              Service: "lambda.amazonaws.com"
            Condition:
              StringEquals:
                aws:SourceAccount: !Sub "${AWS::AccountId}"
